version: "3"
services: 
    app: 
        container_name: bpjstk-app
        restart: always
        build: .
        ports:
            - "3003:3002"
        links: 
            - mongo
        environment: 
            - DB_PATH=${DB_PATH}
            - DB_NAME=${DB_NAME}
            - PORT=${PORT}
            - JWT_SECRET=${JWT_SECRET}
    mongo: 
        container_name: mongoserver
        image: mongo
        ports:
            - "27018:27017"
